### ISSUE TITLE
Ungraceful handling of duplicate keys

### ISSUE THREAD

**Issue by machty** [mirego/accent#132]
I had a duplicate key in my rails_yml file, which caused two entries to be inserted into the database upon `accent_sync`. Once it's in there, it seems to cause a few issues.

One is that when trying to view the translation in the web app, you get 500 errors due to `no function clause matching in Accent.TranslationsRenderer.fetch_master_value/2`; the issue is that the array comes in with a size of 2 due to the duplicates. 

```
2019-12-10T18:12:44.579848+00:00 app[web.1]: ** (FunctionClauseError) no function clause matching in Accent.TranslationsRenderer.fetch_master_value/2
2019-12-10T18:12:44.579851+00:00 app[web.1]: (accent) lib/accent/translations/translations_renderer.ex:52: Accent.TranslationsRenderer.fetch_master_value([%Accent.Translation{__meta__: #Ecto.Schema.Metadata<:loaded, "translations">, comments: #Ecto.Association.NotLoaded<association :comments is not loaded>, comments_count: 0, comments_subscriptions: #Ecto.Association.NotLoaded<association :comments_subscriptions is not loaded>, conflicted: false, conflicted_text: "Apply Automatically", corrected_text: "Apply Automatically", document: #Ecto.Association.NotLoaded<association :document is not loaded>, document_id: "00e32c53-e172-4ef7-a397-339c452e1d4a", file_comment: nil, file_index: 177, id: "990f02c2-090c-4886-ae13-98c083204e55", inserted_at: ~U[2019-12-10 17:04:06.000000Z], key: "active_admin.resources.promotion.auto_apply_rule", locked: false, marked_as_removed: nil, operations: #Ecto.Association.NotLoaded<association :operations is not loaded>, placeholders: [], plural: false, project: #Ecto.Association.NotLoaded<association :project is not loaded>, proposed_text: "Apply Automatically", removed: false, revision: #Ecto.Association.NotLoaded<association :revision is not loaded>, revision_id: "8e417de9-9ac3-45df-9706-3caa9a8788ed", source_translation: #Ecto.Association.NotLoaded<association :source_translation is not loaded>, source_translation_id: nil, text: nil, updated_at: ~U[2019-12-10 18:12:44.000000Z], value_type: "string", version: #Ecto.Association.NotLoaded<association :version is not loaded>, version_id: nil}, %Accent.Translation{__meta__: #Ecto.Schema.Metadata<:loaded, "translations">, comments: #Ecto.Association.NotLoaded<association :comments is not loaded>, comments_count: 0, comments_subscriptions: #Ecto.Association.NotLoaded<association :comments_subscriptions is not loaded>, conflicted: false, conflicted_text: "Apply Automatically", corrected_text: "Auto Apply Rule", document: #Ecto.Association.NotLoaded<association :document is not loaded>, document_id: "00e32c53-e172-4ef7-a397-339c452e1d4a", file_comment: nil, file_index: 177, id: "5295143c-db69-4a27-8b3c-016428e1f999", inserted_at: ~U[2019-12-10 17:04:06.000000Z], key: "active_admin.resources.promotion.auto_apply_rule", locked: false, marked_as_removed: nil, operations: #Ecto.Association.NotLoaded<association :operations is not loaded>, placeholders: [], plural: false, project: #Ecto.Association.NotLoaded<association :project is not loaded>, proposed_text: "Auto Apply Rule", removed: false, revision: #Ecto.Association.NotLoaded<association :revision is not loaded>, revision_id: "8e417de9-9ac3-45df-9706-3caa9a8788ed", source_translation: #Ecto.Association.NotLoaded<association :source_translation is not loaded>, source_translation_id: nil, text: nil, updated_at: ~U[2019-12-10 17:06:52.000000Z], value_type: "string", version: #Ecto.Association.NotLoaded<association :version is not loaded>, version_id: nil}], #Function<1.119560996/1 in Accent.TranslationsRenderer.render/1>)
2019-12-10T18:12:44.579853+00:00 app[web.1]: (accent) lib/accent/translations/translations_renderer.ex:42: anonymous fn/3 in Accent.TranslationsRenderer.fetch_entries/3
2019-12-10T18:12:44.579855+00:00 app[web.1]: (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
2019-12-10T18:12:44.579857+00:00 app[web.1]: (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
2019-12-10T18:12:44.579859+00:00 app[web.1]: (accent) lib/accent/translations/translations_renderer.ex:8: Accent.TranslationsRenderer.render/1
2019-12-10T18:12:44.579861+00:00 app[web.1]: (accent) lib/web/controllers/export_controller.ex:164: Accent.ExportController.fetch_rendered_document/2
2019-12-10T18:12:44.579864+00:00 app[web.1]: (accent) lib/web/controllers/export_controller.ex:1: Accent.ExportController.plug_builder_call/2
```

As a new user I couldn't figure out how to quickly correct for this issue; are there any pro user tips as to how I could have fixed this, perhaps in the console?

**Comment by simonprev** [comment]
I thought that there was a unique index on the database to prevent this case 🤔 

To flag the translation as deleted, you can execute this in an `iex` shell:

```elixir
Accent.Translation
|> Accent.Repo.get("990f02c2-090c-4886-ae13-98c083204e55")
|> Ecto.Changeset.change(removed: true)
|> Accent.Repo.update!()
```

Removed translation are not used in `translations_renderer` so it should not raise an error.

**Comment by simonprev** [comment]
I just pushed a new version of Accent with many fixes (and features)

The error for duplicate should not happen, we now ignore "many" keys in the context of the `TranslationRenderer`

```elixir
  defp fetch_master_value([master_translation | _], value_map) do
    value_map.(master_translation)
  end
```

If `fetch_master_value/2` receives a list containing more than 1 entry, it will just use the first and discard the rest 😄
