### ISSUE TITLE
(RuntimeError) SSL connection can not be established because `:ssl` application is not started

### ISSUE THREAD

**Issue by riverar** [mirego/accent#148]
Attempted to spin up the Docker image with environment variables:
```
DUMMY_LOGIN_ENABLED=0
FORCE_SSL=true
DATABASE_URL=postgresql://xxx@xxx:yyyy@host/accent?ssl=true
```

Resulted in failure, container logs:
```
Running migrations for accent…
** (EXIT from #PID<0.166.0>) an exception was raised:
    ** (RuntimeError) SSL connection can not be established because `:ssl` application is not started,
you can add it to `extra_application` in your `mix.exs`:

  def application do
    [extra_applications: [:ssl]]
  end

        (postgrex) lib/postgrex.ex:538: Postgrex.ensure_deps_started!/1
        (postgrex) lib/postgrex.ex:480: Postgrex.child_spec/1
        (ecto_sql) lib/ecto/adapters/sql.ex:459: Ecto.Adapters.SQL.init/3
        (ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
        (stdlib) supervisor.erl:295: :supervisor.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by riverar** [comment]
I suspect my connection string is completely off here. I am not sure how to configure the app to connect securely to Postgresql. (Required by Azure Database.)

**Comment by simonprev** [comment]
We added support for SSL config: https://github.com/mirego/accent/pull/241
