### ISSUE TITLE
1.7.0 doesn't work - unexpected byte at position 0: 0x65 ('e')

### ISSUE THREAD

**Issue by Fma965** [mirego/accent#226]
```
docker run --name=accent  --env-file .env --net=host mirego/accent:1.7.0
Running migrations for accent…
14:26:46.509 [info] == Running 20191217180708 Accent.Repo.Migrations.AddForeignKeyIndexForOperations.change/0 forward
14:26:46.513 [info] create index operations_rollbacked_operation_id_index
Running seed script for accent…
14:26:48.369 [info] Application goth exited: Goth.start(:normal, []) returned an error: shutdown: failed to start child: Goth.Config
    ** (EXIT) an exception was raised:
        ** (Jason.DecodeError) unexpected byte at position 0: 0x65 ('e')
            (jason 1.2.2) lib/jason.ex:78: Jason.decode!/2
            (goth 1.2.0) lib/goth/config.ex:199: Goth.Config.decode_json/1
            (goth 1.2.0) lib/goth/config.ex:66: Goth.Config.load_and_init/1
            (stdlib 3.13.2) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13.2) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,goth,{{shutdown,{failed_to_start_child,'Elixir.Goth.Config',{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<\"e768b40b2843bf67bc30bebbf9fbdb1f17bfec42\">>,position => 0,token => nil},[{'Elixir.Jason','decode!',2,[{file,\"lib/jason.ex\"},{line,78}]},{'Elixir.Goth.Config',decode_json,1,[{file,\"lib/goth/config.ex\"},{line,199}]},{'Elixir.Goth.Config',load_and_init,1,[{file,\"lib/goth/config.ex\"},{line,66}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,417}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,385}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.Goth',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,goth,{{shutdown,{failed_to_start_child,'Elixir.Goth.Config',{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeEr

Crash dump is being written to: erl_crash.dump...done
```

**Comment by Fma965** [comment]
Nevermind it's because you need to parse the whole json account details for the service account to GOOGLE_TRANSLATIONS_SERVICE_ACCOUNT_KEY not just the ACCOUNT KEY, this should really be named better so that it's clearer.
