### ISSUE TITLE
ERROR 3F000 (invalid_schema_name) schema "public" does not exist

### ISSUE THREAD

**Issue by axelrindle** [mirego/accent#437]
I want to use another Postgres schema than `public` but that doesn't seem to work.

While I fixed another migration in #436 there seems to be yet another problem.

```
13:38:44.320 [info] == Running 20200509183314 Accent.Repo.Migrations.AddObanJobsTable.up/0 forward
13:38:44.343 [info] execute "DO $$\nBEGIN\nIF NOT EXISTS (SELECT 1 FROM pg_type\n               WHERE typname = 'oban_job_state'\n                 AND typnamespace = 'public'::regnamespace::oid) THEN\n    CREATE TYPE \"public\".oban_job_state AS ENUM (\n      'available',\n      'scheduled',\n      'executing',\n      'retryable',\n      'completed',\n      'discarded'\n    );\n  END IF;\nEND$$;\n"
** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "public" does not exist
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
    (stdlib 5.1.1) timer.erl:270: :timer.tc/2
```

**Comment by axelrindle** [comment]
Closed in #436
