### ISSUE TITLE
Production Docker Crypto Not Available

### ISSUE THREAD

**Issue by panbanda** [mirego/accent#70]
Greetings,

I built the image with `make build` and then changed only the ports in the docker-compose file and did `docker-compose up` and I am getting this error related to a dependency:

```
accent         | ":load_failed, Failed to load NIF library: 'Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /opt/accent/lib/crypto-4.4/priv/lib/crypto.so)'"
accent         | OpenSSL might not be installed on this system.
accent         |
accent         | 16:04:02.788 [warn] The on_load function for module crypto returned:
accent         | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library libcrypto.so.1.1: No such fileor directory (needed by /opt/accent/lib/crypto-4.4/priv/lib/crypto.so)\''}}
accent         | ▸  Evaluation failed with: function :crypto.strong_rand_bytes/1 is undefined (module :crypto is not available)
accent         | ▸      (crypto) :crypto.strong_rand_bytes(16)
accent         | ▸      (ecto) lib/ecto/uuid.ex:165: Ecto.UUID.bingenerate/0
accent         | ▸      (ecto) lib/ecto/repo/schema.ex:154: Ecto.Repo.Schema.autogenerate_id/4
accent         | ▸      (ecto) lib/ecto/repo/schema.ex:84: anonymous fn/5 in Ecto.Repo.Schema.extract_header_and_fields/5
accent         | ▸      (elixir) lib/enum.ex:1418: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
accent         | ▸      (ecto) lib/ecto/repo/schema.ex:82: Ecto.Repo.Schema.extract_header_and_fields/5
accent         | ▸      (ecto) lib/ecto/repo/schema.ex:44: Ecto.Repo.Schema.do_insert_all/6
accent         | ▸      (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```

I haven't changed the repo at all and am just wondering if you can reproduce it on your end as well?  I was able to do it on two machines.

**Comment by gcauchon** [comment]
This is a side effect to the `elixir:1.7-alpine` image being updated to `erlang:21-alpine` which is now based on `alpine:3.9` instead of `3.8`. I`m going to submit a pull request in the next minutes to upgrade the Docker configuration and add the missing dependencies.

**Comment by panbanda** [comment]
Sounds great thank you.  I had just started going through all the various dependencies, would have taken me a while!  Appreciate it.
